// BOT MESSAGES
export const SEND_BOT_MESSAGE = "SEND_BOT_MESSAGE";
export const SEND_BOT_MESSAGE_SUCCESS = "SEND_BOT_MESSAGE_SUCCESS";
export const SEND_BOT_MESSAGE_FAILED = "SEND_BOT_MESSAGE_FAILED";
