// BOT MESSAGES
export const SEND_BOT_MESSAGE = "SEND_BOT_MESSAGE";
export const SEND_BOT_MESSAGE_SUCCESS = "SEND_BOT_MESSAGE_SUCCESS";
export const SEND_BOT_MESSAGE_FAILED = "SEND_BOT_MESSAGE_FAILED";

// AUTHENTICATION
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_FAILED = "LOGIN_ADMIN_FAILED";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";
